env:
  node: true
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2017
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
  - 'ngeor'
rules:
  # Vue
  vue/html-indent:
    - error
    - 4
