default:
  - pre-commit
pre-commit:
  - jsonlint
  - lintspaces
  - eslint
  - csharplint:pre-commit
  - coverage
  - xml_check
  - postcss

coverage:
  - mocha_istanbul
  - istanbul_check_coverage
ci:
  - clean
  - sca-ci
  - build #Release
  - test
  - doc
  - export-environment-variables
  - loc
  - browserify
  - sass
build:
  - replace:assemblyInfo
  - msbuild:main
sca-ci:
  - jsonlint
  - lintspaces
  - eslint
  - csharplint:ci
  - xml_check
  - postcss
test:
  - test-js
  - nunitNoIntegration
test-js:
  - mochaTest:ci
  - mocha_istanbul
  - istanbul_check_coverage
doc:
  - jsdoc
dist:
  - distWeb
  - distCrawler
  - compress
distWeb:
  - copy:distWeb
  - shell:xdtWebConfig
distCrawler:
  - copy:distCrawler
  - shell:xdtCrawlerConfig
