language: csharp
solution: src/BuzzStats.sln
install:
  - sudo apt-get install g++ build-essential
  - nvm install node
  - nvm use node
  - npm install -g grunt-cli
  - npm install
  - nuget restore src/BuzzStats.sln
