language: csharp
solution: BuzzStats.sln
install:
- nvm install node
- nvm use node
- nuget restore BuzzStats.sln
- cd client && npm install && cd ..
script:
- msbuild /p:Configuration=Debug BuzzStats.sln
- cd client && npm test && cd ..
