language: java
jdk: oraclejdk8
after_success:
- mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
env:
  global:
    secure: Irb9U1U1Gyap65wv4xEp7SWjGStNq6V8ueicqvoGN/pBSdKRjMfc1bu1hiT1s2k8ETEWMEHjJHsKsCKQuhMeOd0QaTCvFpFvDxcNrfq4KI1jjuNsAXzc6cG2rc3nz7g25zlDjGspuVyG2ySbrpjRsTAG1VCn8qbpmqm9FhrA0YpHrLJdQDe3SNKDz38+Nzw//QNTr9gyiOKpKEcuFq8k1B13rk3GuC1niZNje6IEQQaNicF42v/K4E42GPIQw5y4F3cllBQmhKowdVR6gINgE8mA8TAPFeKkhMuGQ1UVT5Fputm3JQCv+XwCJBfBR2u00b4HkK+sqe0zuDkkSgTmveqsKbBODXnPXEO4UKTNo0A5O+Xk+WqS2+3G1vS3BYlz1q5xDsWxR6G0dhShwfo3RT31Lbe2z22zUL8yTiB+Aggk+t5wv6rNdjRqxP3ixgORTmXIJ+4MZ9cjFBLw+irSfKaLKFGLavO1Jly5gQBHF8RmufDAWSNOcL6wWOW8vQiXIlhCJJ1LsxlDHlF7MXjtzxtEer9JNXTqQmUypw8D1cXu+Qpkt85GJEv9fkpGMT191YIVdod5Y1iLRyi2m3C1GqmKxupRsXn2h4NWMeSG2Z9W2Aug386qmRyTYqX7l2EOjdOLY7CJDN0zHFI+rFtFeKuUwKiN/R5n55z4FvVrbho=
