language: csharp
solution: BuzzStats.sln
install:
- nvm install node
- nvm use node
- npm install -g gulp-cli
- nuget restore BuzzStats.sln
- cd BuzzStats.WebApi && npm install && cd ..
script:
- msbuild /p:Configuration=Debug BuzzStats.sln
- cd BuzzStats.WebApi && gulp && cd ..
