language: csharp
install:
- nvm install node
- nvm use node
- cd server && nuget restore BuzzStats.sln && cd ..
- cd client && npm install && cd ..
script:
- cd server
- msbuild /p:Configuration=Debug BuzzStats.sln
- cd ../client
- npm test
- cd ..
