version: 2.0.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: kGjvvsi37IZdw7VuwblEoP1aydS4RyDMUtEJiXe1v2zUMoYkBM7isPNXqVlOA+Ii
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
before_build:
  - nuget restore BuzzStats.sln
build:
  parallel: false
  project: BuzzStats.sln
test:
  assemblies:
    only:
      - '**\*UnitTests.dll'
after_test:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[*.UnitTests]*" -target:.\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe -targetargs:".\BuzzStats.MockServer.UnitTests\bin\Debug\BuzzStats.MockServer.UnitTests.dll .\BuzzStats.ParserWebApi.UnitTests\bin\Debug\BuzzStats.ParserWebApi.UnitTests.dll .\BuzzStats.CrawlerService.UnitTests\bin\Debug\BuzzStats.CrawlerService.UnitTests.dll .\BuzzStats.StorageWebApi.UnitTests\bin\Debug\BuzzStats.StorageWebApi.UnitTests.dll"
  - .\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i .\results.xml
