version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yourStrongPassword1_
      - MYSQL_DATABASE=BuzzStats
      - MYSQL_USER=buzzstats
      - MYSQL_PASSWORD=#buzzstats#
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
