version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  mongo:
    image: mongo
    ports:
      - 27017:27017
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - DB_HOST=mongo
  buzzstats.listingester:
    image: buzzstats.listingester
    build:
      context: .
      dockerfile: BuzzStats.ListIngester/Dockerfile
    environment:
      - BROKERLIST=192.168.99.100
      - CONNECTIONSTRING=mongodb://mongo:27017
  buzzstats.storyingester:
    image: buzzstats.storyingester
    build:
      context: .
      dockerfile: BuzzStats.StoryIngester/Dockerfile
    environment:
      - BROKERLIST=192.168.99.100
      - CONNECTIONSTRING=mongodb://mongo:27017
  buzzstats.storyupdater:
    image: buzzstats.storyupdater
    build:
      context: .
      dockerfile: BuzzStats.StoryUpdater/Dockerfile
    environment:
      - BROKERLIST=192.168.99.100
      - CONNECTIONSTRING=mongodb://mongo:27017
  buzzstats.changetracker:
    image: buzzstats.changetracker
    build:
      context: .
      dockerfile: BuzzStats.ChangeTracker/Dockerfile
    environment:
      - BROKERLIST=192.168.99.100
      - CONNECTIONSTRING=mongodb://mongo:27017
  buzzstats.web:
    image: buzzstats.web
    build:
      context: .
      dockerfile: BuzzStats.Web/Dockerfile
    ports:
      - 9000:9000
    environment:
      - BROKERLIST=192.168.99.100
      - CONNECTIONSTRING=mongodb://mongo:27017
