version: '3'

services:
  buzzstats.listingester:
    image: buzzstats.listingester
    build:
      context: .
      dockerfile: BuzzStats.ListIngester/Dockerfile
    environment:
      - KAFKA_BROKER=192.168.99.100
  buzzstats.storyingester:
    image: buzzstats.storyingester
    build:
      context: .
      dockerfile: BuzzStats.StoryIngester/Dockerfile
    environment:
      - KAFKA_BROKER=192.168.99.100
  buzzstats.changetracker:
    image: buzzstats.changetracker
    build:
      context: .
      dockerfile: BuzzStats.ChangeTracker/Dockerfile
    environment:
      - KAFKA_BROKER=192.168.99.100
      - MONGO=192.168.99.100:27017
  buzzstats.web:
    image: buzzstats.web
    build:
      context: .
      dockerfile: BuzzStats.Web/Dockerfile
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKER=192.168.99.100
