version: '3'
services:
  mysql:
    build: ../mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yourStrongPassword1_
      - MYSQL_DATABASE=BuzzStats
      - MYSQL_USER=buzzstats
      - MYSQL_PASSWORD=#buzzstats#
    volumes:
      - ../mysql/data:/var/lib/mysql
